remote_theme : mmistakes/minimal-mistakes
url                      : "https://minimaxa.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : ""
# theme: jekyll-theme-dinky
